version: "1.0"
services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-container
    hostname: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: senha123
    volumes:
      - ./mariadb/:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - mariadb
  php:
    build: "./dockerfiles/php"
    container_name: php-container
    volumes:
      - ./php:/var/www/html
    ports:
      - "8082:80"
